esphome:
  name: gun
  friendly_name: "Nerf Gun"
  comment: "Automatic Nerf Gun"
esp8266:
  board: d1_mini

wifi:
  ssid: !secret WiFi_network
  password: !secret wifi_password
  manual_ip:
     static_ip: 192.168.1.221
     gateway: 192.168.1.1
     subnet: 255.255.255.0
     dns1: 192.168.1.1

  ap:
    ssid: "Nurf-Gun Fallback Hotspot"
    password: "DibiUQCWJXqo"

logger:

api:
  encryption:
    key: "bbRGearzkb00E3KcLYkwMxla2fcYmSNTMVESQ5zPJUw="

ota:
  - platform: esphome
    password: "af4707963e1f5af22b09695c56d56588"

captive_portal:

web_server:
  port: 80

mqtt:
  broker: 192.168.1.200
  username: !secret mqtt_username
  password: !secret mqtt_password


switch:
  - platform: gpio
    pin:
      number: D6
      inverted: yes
    name: "nurfgun"
    id: feed
    on_turn_on: 
      - delay: 0.5s
      - switch.turn_on: fire
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: D7
      inverted: yes
    name: "fire"
    id: fire
    # on_turn_on: 
    #   - delay: 0.3s
    #   - switch.turn_off: fire
    #   - delay: 0.3s
    #   - switch.turn_off: feed
    # restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    device_class: running
    name: "Button"
    pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: True
